### ISSUE TITLE
gtk3-classic causes gtk_widget_is_visible: assertion 'GTK_IS_WIDGET (widget)' failed

### ISSUE THREAD

**Issue by ryanmusante** [manjaro/packages-extra#165]
gtk3-classic causes fatal error in application with spamming in journalctl with errors. Replacing with standard gtk3 package fixes. Unknown how many other applications are affected.
```
~ >>> sudo pacman -Qo /usr/lib/libgtk-3.so.0                                                                        
[sudo] password for ryan:
/usr/lib/libgtk-3.so.0 is owned by gtk3-classic 3.22.30-0.1
```
Reference to https://github.com/gnome-mpv/gnome-mpv/issues/355
```
Starting program: /usr/bin/gnome-mpv --g-fatal-warnings
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffce088700 (LWP 29987)]
[New Thread 0x7fffcd887700 (LWP 29988)]
[New Thread 0x7fffcca0f700 (LWP 29989)]
[New Thread 0x7fffbf960700 (LWP 29990)]
[New Thread 0x7fffbf15f700 (LWP 29992)]
[New Thread 0x7fffbe95e700 (LWP 29993)]
[New Thread 0x7fffbe15d700 (LWP 29994)]

(gnome-mpv:29889): Gtk-CRITICAL **: 22:11:38.686: gtk_widget_is_visible: assertion 'GTK_IS_WIDGET (widget)' failed

Thread 1 "gnome-mpv" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff5de7ed2 in ?? () from /usr/lib/libglib-2.0.so.0
#0  0x00007ffff5de7ed2 in  () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff5de923d in g_logv () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff5de93a0 in g_log () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff74925bb in gtk_widget_is_visible () at /usr/lib/libgtk-3.so.0
#4  0x0000555555577f33 in  ()
#5  0x00007ffff5de2cb3 in  () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff5de21d6 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff5de25b1 in  () at /usr/lib/libglib-2.0.so.0
#8  0x00007ffff5de263e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff63a397e in g_application_run () at /usr/lib/libgio-2.0.so.0
#10 0x00005555555608e3 in main ()
(gdb) 
```

**Comment by oberon2007** [comment]
@TomaszGasior

**Comment by TomaszGasior** [comment]
I will investigate the problem today. Sorry for inconvenience!

**Comment by TomaszGasior** [comment]
Fixed. https://forum.manjaro.org/t/gtk3-classic-gtk3-mushrooms-gtk3-with-my-own-patches/30230/100

**Comment by ryanmusante** [comment]
Very nice, thank you!
